### ISSUE TITLE
ZFR Submission

### ISSUE THREAD

**Issue by Oterem** [yeseg11/Let-it-know#18]
1## Feature Template

#### TODO issues
- [ ] #11 Add recommendations to recommened list.  **moved to iteration 3**
- [ ] #12 Delete recommendations from recommened list.  **moved to iteration 3**
- [ ] #13 Adding and granting permissions to organizations. **moved to iteration 3**
- [x] #14 administator log in.
- [x] #15 Delete authorised organizations from system's list.
- [x] #16  Add event to calendar
- [x] #17 Present events to users.

#### Need To Do (ZFR HW 3)
- [x] שלבי העבודה - שגיא ועמרי 
- [x] בקרת גרסאות – Version Control - זאב
- [x] אב טיפוס - עמרי 
- [x] תיעוד המוצר - מיתר
- [x] סקר ZFR - אבי
- [x] תכנון סבב 1- זאב שגיא ועמרי

Project Submission Template
#### Checklist, e.g.,:
- [x] Feature scenarios/tests passing
- [x] Iteration page updated, including:
  - [x] Iteration retrospective
  - [x] Code reviewes
  - [x] Client review
  - [x] Issues updates
  - [x] Section on application of course materials

- [x] Next iteration:
  - [x] Open page
  - [x] Select stories and plan issues
  - [x] Test scenarios
- [x] All engineers filled peer-review 
- [x] Submitted
  - [x] Announcement in chat room
  - [x] Assign this issue to checker
  - [x] Register for a review meeting
