### ISSUE TITLE
Iteration 3

### ISSUE THREAD

**Issue by Oterem** [yeseg11/Let-it-know#33]
#### TODO issues

- [x] #26 Improve the UI for FullCalendar.
- [x] #34 Render events which are within 2 months.
- [x] #48 Fix iOS render bug.
- [x] #49 Add android application.
- [x] #57 Change the project name from "let it know" into "coming out". 

#### Need To Do 
- [x] Upgarde calendar view using bootstrap or other design tools. - @yeseg11, @avicohen89, @meitarsh 
- [x] Set the system to sync and present events in a 60 days radius. @Chaosruler972, @Oterem
