### ISSUE TITLE
Iteration  2

### ISSUE THREAD

**Issue by yeseg11** [yeseg11/Let-it-know#35]
#### TODO issues
- [x] #32 Remove the 'admin' button from UI on manage users .
- [x] #30 Fix URL on manual event .
- [x] #27 Add Google Calendar support .
- [x] #23 Display calendar view (monthly or agenda).
- [x] #17 Present events to users.

#### Need To Do 
- [x] Fix URL on manual event - zeev - @Chaosruler972 
- [x] Add Google Calendar support -sagi - @yeseg11
- [x] Display calendar view - Avi- @avicohen89  
- [x] Present events to users - Omri - @Oterem 
- [x] Remove the 'admin' button from UI on manage users - mortar - @meitarsh

**Comment by yeseg11** [comment]
Finish all
