### ISSUE TITLE
Iteration 4

### ISSUE THREAD

**Issue by yeseg11** [yeseg11/Let-it-know#36]
1## Feature Template

#### TODO issues
- [x] #56  Prepare the application to upload into the Google market.
- [x] #55 Pull data using SQLite.
- [x] #54 Add "about" page.
- [x] #53 Parse data between two activities.
- [x] #52 Render events on Android calander using new API's.
- [x] #51 Convert JS UI into Android UI.
- [x] #50 Move login button ito hidden menu.
