### ISSUE TITLE
 Iteration 1 - Prototype app ready

### ISSUE THREAD

**Issue by yeseg11** [yeseg11/Let-it-know#37]
#### TODO issues
- [x] #29 Add location to database on manual event and on display.
- [x] #22 Synch events from predefined Facebook pages.
- [x] #31  Render events which are within 2 months radius from now on.
- [x] #28  Fix "Pending" button on manual event bug.
- [x] #16 Add event to the Calendar.
- [x] #13  Adding and granting permissions to organizations.
- [x] #15 Delete authorized organization from system's list.
- [x] #14 Administrator log in.
- [x] #21 Fix Facebook Page manager.
 

#### Need To Do (sit all the group and do it ) @Chaosruler972 , @avicohen89 , @meitarsh  , @Oterem 
- [x]  Add location to database on manual event and on display.
- [x]  Synch events from predefined Facebook pages.
- [x]  Render events which are within 2 months radius from now on.
- [x]   Fix "Pending" button on manual event bug.
- [x]  Add event to the Calendar.
- [x]   Adding and granting permissions to organizations.
- [x]  Delete authorized organization from system's list.
- [x]  Administrator log in.
- [x]  Fix Facebook Page manager.
