### ISSUE TITLE
first time Issues

### ISSUE THREAD

**Issue by yeseg11** [yeseg11/Let-it-know#4]
Todo: delete all unnecessary items, add suitable labels (with priotity and estimation), milestone, assignee, etc.
#### Related Issues/Tasks
- [x] #1 first meeting with "open house for pride and tolerance" contact guy.
- [x] #2  creating wiki and modify it . 
- [x] #3   update README.md .  
- [x] #4    update the Project Inception page in Wiki : 
                1.First Planning and Assessment - a list of steps and tasks principal that you think           make the project so that it will be ready at the end of the semester.
                2.Risk management.
                3.Details of the development process.
                4.First features list.
                5.How to share the code ? 
                6.What is the main Ingredients in the product:add diagram .

   

#### Checklist, e.g.,:
- [x] Feature scenarios/tests passing
- [x] Iteration page updated, including:
  - [x] Iteration retrospective
  - [x] Code reviewes
  - [x] Client review
  - [x] Issues updates
  - [x] Section on application of course materials
- [x] git tag
- [x] Next iteration:
  - [x] Open page
  - [x] Select stories and plan issues
  - [x] Test scenarios
- [x] All engineers filled peer-review 
- [x] Submitted
  - [x] Announcement in chat room
  - [x] Assign this issue to checker
  - [x] Register for a review meeting

**Comment by Oterem** [comment]
All done.

**Comment by Oterem** [comment]
checked all done
