### ISSUE TITLE
SDS - Software Design Specification 

### ISSUE THREAD

**Issue by Oterem** [yeseg11/Let-it-know#9]
Todo: delete all unnecessary items, add suitable labels (with priotity and estimation), milestone, assignee, etc.
#### Related Issues/Tasks
- [x]  #1 UML 
- [x] #2 State Charts
- [x] #3 Main page
- [x] #4 CRC
- [x] #5 Dependecies of working process
- [x] #6 User Manual
- [x] #7 Non-functional requirements
- [x] #8 Capabilities - update risk managment
#### Scenario (test)
- [ We had common dependecies ] Step 1
- [ We divided our dependecies] Step 2
- [ Completed software design setup] Expected result

## User Story Template
- As a a developer
- I want to know how my software is designed while programming
- So that I can answer questions while developing that rises up.

#### Expected behavior

Different files containing the design of the software, the design should contain all the classes theoriticilly required to write the software,

**Comment by Oterem** [comment]
first SDS

**Comment by Oterem** [comment]
all done @kob-e

**Comment by yeseg11** [comment]
all done @kob-e 

can we close it ?
